version: "3.9"
services:
  frontend:
    build: ./frontend
  backend:
    build: ./backend
    env_file: .env
    depends_on: [mongo]
  mongo:
    image: mongo
    volumes: [mongo:/data/db]
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: ["80:80"]
    depends_on: [frontend,backend]
volumes:
  mongo: